### ISSUE TITLE
New-DrsVMtoVMHostRule setting affinity correctly?

### ISSUE THREAD

**Issue by rcooper3** [PowerCLIGoodies/DRSRule#10]
For New-DrsVMtoVMHostRule the -AffineHostGroupName switch seems to set a new rule to be anti-affinity and -AntiAffineHostGroupName is setting it to be affinity?

e.g.
New-DrsVMToVMHostRule -Name licencing_windows_vmhostrule -Cluster $cluster -VMGroupName licencing_windows_vmgroup -**AntiAffine**HostGroupName licencing_windows_hostgroup -whatif
What if: Performing the operation "**Create Affine**VMToVMHost DRS rule 'licencing_windows_vmhostrule'" on target "cluster1".

vs

New-DrsVMToVMHostRule -Name licencing_windows_vmhostrule -Cluster $cluster -VMGroupName licencing_windows_vmgroup -**Affine**HostGroupName licencing_windows_hostgroup -whatif
What if: Performing the operation "**Create AntiAffine**VMToVMHost DRS rule 
 licencing_windows_vmhostrule'" on target "cluster1".

**Comment by rcooper3** [comment]
Appears to only effect whatif results. In practice the command behaves as expected.

**Comment by mtboren** [comment]
Thanks, @rcooper3, for reporting this issue in the `WhatIf` and `Verbose` output. I just made commit 8ace2dcea58272d3bc57e8ef11fd64ba70188c23 that addressed the issue. Next release will include this fix.

Cheers,

Matt
