### ISSUE TITLE
Metadata file VMware.Vim.dll could not be found

### ISSUE THREAD

**Issue by Sader82** [PowerCLIGoodies/DRSRule#15]
I installed vmware module wit NuGet and it turnsout that VMware.Vim.dll is put in a subdirectory net45. your code:

$strVMwareVimDllDirectory = if ($oModuleInfo.Version -ge $verPowerCLIWhereDllMoved) {$oModuleInfo.ModuleBase} else {(Get-Item (Get-Module VMware.VimAutomation.Core).ModuleBase).Parent.Parent.FullName}

$pcliDll = Join-Path -Path $strVMwareVimDllDirectory -ChildPath "VMware.Vim.dll"

your code does not check for the net45 or netcoreapp2.0 folder.

**Comment by mtboren** [comment]
Same issue when using PowerCLI 10 -- the named .dll is elsewhere. Need to fix
