### ISSUE TITLE
VMware.VimAutomation.Core path change in 6.5.1

### ISSUE THREAD

**Issue by jmegie** [PowerCLIGoodies/DRSRule#9]
Just downloaded the latest PowerCLI and ran into issues:

PowerCLI Version
----------------
   VMware PowerCLI 6.5.1 build 5377412
---------------
Component Versions
---------------
   VMware Cis Core PowerCLI Component 6.5 build 5374323
   VMware VimAutomation Core PowerCLI Component 6.5 build 5374329

I manually modified $pcliDLL path in DRSRule.init.ps1 to fix the issue. 

If new PowerCLI modules are installed to current user (via 6.5.1 user guide: Install-Module VMware.PowerCLI -Scope CurrentUser), then path is (for this build) $HOME\documents\WindowsPowerShell\Modules\VMware.VimAutomation.Core\6.5.1.5374329, if installing for all users it's Program Files\WindowsPowerShell\Modules\VMware.VimAutomation.Core\6.5.1.5374329

Obviously the version/build directory name will change with the new way PowerCLI/Modules are being delivered, so it might be best to get/store the version number in a variable in the path.

**Comment by mtboren** [comment]
Hello, @jmegie -

Yes, thank you for opening an issue for this.  @lucdekens also spotted this, and has mentioned some intention to rectify this.  We'll get it fixed and released.

**Comment by mtboren** [comment]
Made commit 56b7f52e2cf933196d8c117d624a96acf203f316 that updates code that determines the location of the referenced `VMware.Vim.dll` file, based on PowerCLI module version. Tested with PowerCLI 6.3, 6.5rel1, and 6.5.1.
